### ISSUE TITLE
Weekly Breakdown

### ISSUE THREAD

**Issue by ella-irene** [UBC-MDS/DSCI-532_2024_18_VancouverAirbnbPrices#2]
Roles this week:
- Repo Setup : @wenyunie 
- Submission : @Kierst01 
- Readme Update : @ella-irene 

Motivation - @ella-irene 
Target audience: People who are living or looking to get a place in Vancouver.
Role: Data Scientists working for Strathcona County government.
Why is our question important:
Since the housing price in Vancouver fluctuates very frequently and unexpectedly, and also known that Vancouver is growing in its popularity, it is important for people who wish to move to Vancouver to gauge how much they will have to pay for getting a property. 
How can your dashboard help in solving the problem?
By plotting out the trend and distribution of housing prices, and also by providing a prediction of property assessment. 

Data Description -@wenyunie
Open source housing assessment data from 2019 - 2024
(fill in variable description)

Research Questions - @Kierst01 
What is the mean housing price for houses in each region in Vancouver?
Users are expected to use this dashboard to investigate housing trends in vancouver, either to inform decisions on where to rent or buy houses

App Sketch/ description - @jlee2843

**Comment by wenyunie** [comment]
Roles this week(Week2):

Deployment on render : @wenyunie

Components:
1. Filtering section (3+ components): @jlee2843 
2. Time Series related section (1+): @wenyunie 
3. Map (1+): @ella-irene 
4. Summary Statistics(1+): @Kierst01 
5. Prediction Tab (Maybe Later if we have time)

Reflection: @Kierst01  Friday
leave time for Kiersten to write reflection
noon meeting at 1 (things ready for writing reflection)

Readme: @jlee2843

**Comment by Kierst01** [comment]
To do list for week 3:

1. Fix map to display with default values [Ella]
2. Improve map functionality (colours, tooltip) [Ella]
3.  Fix summary stats to display with default values [Kiersten]
4. Add a tab with histograms of categorical variables to summary stats [Kiersten]
5. For prediction tab add map of given longitude and latitude coordinates [Jenny]
6. Fix picture layout in credentials tab [Wenyu] [Done]
8. Reflection [Ella]
9. improves the trends section: 1) default trend more realistic, 2) hyperlink, 3) simplify the metric list, 4) linetype 5) fix the global filtering conditions in the viewpoint when scrolling down [Wenyu] [Done]
11. predictive model: make it robust when there are missing values [Wenyu] [Done]
12. Multiple files breakdown [Everyone who would like to separate their codes out, Done]
13. look into the map selection triggering summary and trend change part, if it is implementable try it [optional, Wenyu, Done]

Submission: Jenny
Next meeting: Thursday, 1:30 PM

**Comment by wenyunie** [comment]
I will also try to figure out if it is possible to fix the filtering side section there in the viewpoint (would need Jenny's review if there is a PR)
