### ISSUE TITLE
Feedback from Joel

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_18_VancouverAirbnbPrices#52]
Major:
- [x] Main view is map and point color is price, so that locations can be compared
- [x] Make map interval selection that filters the data further after the widget selections are applied.

Minor:
- [x] Capitalize names in tbale
- [ ] Color code maps based on neighborhood
- [ ] Color based on neighbood
- [x] Zoom map / fix margins
- [x] Make numbers in cards a big bigger
    - [x] Consider showing median?

**Comment by ella-irene** [comment]
A note on the color code of the neighborhoods:
While we were planning on coloring by neighborhood in our discussion with Joel, we ultimately decided that coloring by price was a better choice, as it added more visual information to our map.
