### ISSUE TITLE
Feedback from Joel M4

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_18_VancouverAirbnbPrices#75]
Implement either two major and four minor, or three major and one minor

Major:

- [x] #100
- [x] Make invisible map legend also filter shown map @ella-irene 
- [x] #87

Minor:

- [x] Make selection persistent, e.g. color points  @wenyunie 
https://github.com/UBC-MDS/DSCI-532_2024_18_VancouverAirbnbPrices/pull/82
- [x] #96
- [x] Default state filter @ella-irene 
- [x] #86
- [x] Indication when widget filters don't match any data (@wenyunie for the trend section) 
https://github.com/UBC-MDS/DSCI-532_2024_18_VancouverAirbnbPrices/pull/82
- [x] "inf" -> actual max price @ella-irene 
- [x] #99
- [x] #93

**Comment by ella-irene** [comment]
Addressed all
